name: 'sentinela'
version: '1.0.0'
config-version: 2
profile: 'sentinela_profile'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sentinela:
    staging:
      materialized: view
    marts:
      materialized: table
